version : '2'

services:
  # mongodb24:
  #   container_name: phpmongo_mongo24
  #   image: mongo:2.4
  #   volumes:
  #     - ../share/mongo24:/data/db
  # mongodb26:
  #   container_name: phpmongo_mongo26
  #   image: mongo:2.6
  #   volumes:
  #     - ../share/mongo26:/data/db
  # mongodb30:
  #   container_name: phpmongo_mongo30
  #   image: mongo:3.0
  #   volumes:
  #     - ../share/mongo30:/data/db
  # mongodb32:
  #   container_name: phpmongo_mongo32
  #   image: mongo:3.2
  #   volumes:
  #     - ../share/mongo32:/data/db
  # mongodb33:
  #   container_name: phpmongo_mongo33
  #   image: mongo:3.3
  #   volumes:
  #     - ../share/mongo33:/data/db
  mongodb34:
    container_name: phpmongo_mongo34
    image: mongo:3.4
    volumes:
      - ../share/mongo34:/data/db
  mongodb429:
    container_name: phpmongo_mongo429
    image: mongo:4.2.9
    volumes:
      - ../share/mongo429:/data/db
  # php56:
  #   image: php:5.6
  #   container_name: phpmongo_php56
  #   command: bash /phpmongo/docker/bootstrap.sh
  #   depends_on:
  #     - mongodb24
  #     - mongodb26
  #     - mongodb30
  #     - mongodb32
  #     - mongodb33
  #     - mongodb34
  #     - mongodb429
  #   volumes:
  #     - ..:/phpmongo
  #     - ./php.ini:/usr/local/etc/php/php.ini
  #   environment:
  #     PHP_IDE_CONFIG: "serverName=phpmongo"
  #     XDEBUG_CONFIG: "idekey=PHPSTORM remote_autostart=1 remote_enable=1 remote_host=dockerhost remote_port=9001"
  #     PHPMONGO_DSN: monfodb://mongodb34
  php749:
    image: webdevops/php-dev:7.4
    container_name: phpmongo_php749
    command: bash /phpmongo/docker/bootstrap.sh
    depends_on:
      # - mongodb24
      # - mongodb26
      # - mongodb30
      # - mongodb32
      # - mongodb33
      - mongodb34
      - mongodb429
    volumes:
      - ..:/phpmongo
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_IDE_CONFIG: "serverName=phpmongo"
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_autostart=1 remote_enable=1 remote_host=dockerhost remote_port=9001"
      PHPMONGO_DSN: monfodb://mongodb429